In [68]:
import os
import sys
import csv
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

repo_root = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
sys.path.append(repo_root)

from src.utils.file_handlers import read_file_parameters

In [69]:
def convergence_file_handlers():
    data_path = os.path.join(os.getcwd(), 'data')

    all_results = []
    for file in os.listdir(data_path):

        id, _ = file.split('_data.csv')
        if file.endswith('.csv'):
      
            
            file_path = os.path.join(data_path, file)
            df = pd.read_csv(file_path)
            iteration = df['HO_iterations'].mean() 
            std = df['HO_iterations'].std()

            result = {'dataset':id, 
                      'C': iteration, 
                      'C_std': std}

            all_results.append(result)

    final_df = pd.DataFrame(all_results)
    final_df['dataset'] = pd.to_numeric(final_df['dataset'], errors='coerce')
    return final_df.sort_values(by='dataset')

def visualize_df(df, title):
    print(f"\n{title}\n")
    styled_df = df.style.set_table_styles(
    ).set_properties(**{
        'background-color': 'LightGray',
        'color': 'black',
        'border-color': 'black',
        'border-style': 'solid',
        'border-width': '1px',
        'text-align': 'left'
    })
    
    styled_df = styled_df.set_table_styles([
        {'selector': 'th.row_heading, th.blank', 'props': [('display', 'none')]}
    ])
    
    styled_df = styled_df.format(precision=4)
    

    # print(df.to_latex(escape=True))
    display(styled_df)

In [70]:
df = convergence_file_handlers()
df.to_csv('results/convergence_table.csv')


python_df = pd.read_csv(os.path.join(repo_root, 'exp', 'ex08', 'results', 'convergence_table.csv'))

merged = pd.merge(df, python_df[['dataset', 'Ours']], on='dataset')
merged = merged.rename(columns={'Ours': 'python'})

In [71]:
title = "Convergence Results of C code "
visualize_df(merged, title)

Convergence Results of C code